apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-store-service
  labels:
    app: image-store-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-store-service
  template:
    metadata:
      labels:
        app: image-store-service
    spec:
      containers:
        - name: image-store-service
          image: aravindhsz/image-store-service:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: image-store-service
  labels:
    app: image-store-service
spec:
  type: NodePort
  selector:
    app: image-store-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080    